main: ru.nilsson03.anarchyregions.AnarchyRegions
api-version: 1.16
version: '${project.version}'
name: AnarchyRegions
authors:
  - Nilsson03
depend:
  - BaseLibrary
commands:
  ps:
    usage: /ps invite <ник> <номер>
    description: Основная команда плагина